export const GET_POKES = 'GET_POKES';
export const GET_POKES_DETAILS = 'GET_POKES_DETAILS';
export const ACTIVE_PAGE = 'ACTIVE_PAGE';
export const NUMBER_TOTAL_PAGES = 'NUMBER_TOTAL_PAGES';
export const CHANGE_ITEMS_PER_PAGE = 'CHANGE_ITEMS_PER_PAGE';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const GET_DETAILS = 'GET_DETAILS';